default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "<your_snowflake_account>"
      user: "<your_username>"
      password: "<your_password>"
      role: "<your_role>"
      database: "ADEBNEYDEMODB"
      warehouse: "<your_warehouse>"
      schema: "DBT_ADEBNEY_P2"
      threads: 4
      client_session_keep_alive: false
      query_tag: "dbt_my_new_project_p2"
      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: true
      retry_all: false
      reuse_connections: true
